[project]
name = "3-spark-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chispa>=0.11.1",
    "pyspark[sql]>=4.0.0",
    "pytest>=8.4.1",
]
